path = "./db"
max_open_files = -1
fsync = false
bytes_per_sync = 0
disable_data_sync = false
optimize_for_point_lookup = 1024
num_shard_bits = 6
max_write_buffer_number = 2
write_buffer_size = 67108864
target_file_size_base = 67108864
min_write_buffer_number_to_merge = 1
level_zero_stop_writes_trigger = 24
level_zero_slowdown_writes_trigger = 20
compaction_style = "Level"
#block based
use_cache = true
cache_defaults = true
cache_size = 100000
block_cache = 10000
bloom_filter_bits_per_key = 8
bloom_filter_block_based = true
index_type = "binarysearch"

